### ISSUE TITLE
Mac OSX cp --preserve=timestamps error

### ISSUE THREAD

**Issue by RichardWatts** [Washington-University/Pipelines#27]
In FreeSurfer/Pipelines/scripts/ FreeSurferHiresPial and FreeSurferHiresWhite:
cp --preserve=timestamps $SubjectDIR/$SubjectID/surf/lh.pial ...

This causes an error on Mac OSX El Capitan (and earlier versions, I would strongly suspect). It looks like this was changed in March, and broke Mac compatibility. It seems as if the option --preserve is only available using Gnu CoreUtils. I'm not sure what the problem was with the previous -p option.

This caused a lot of frustration and head scratching!

Thanks -

Richard

**Comment by tbbrown** [comment]
The `-p` option for the `cp` operation attempts to preserve not only timestamps on files copied, but also ownership and access modes. 

The actual point of adding the `-p` option in the first place was to preserve the timestamps on the files copied. Using the `-p` option works fine for that but also tries to preserve other attributes of the file. In some cases in which the files are being copied, the ownership of the file cannot be maintained. This is what was happening here (at Washington University). Since the ownership could not be maintained in this copy operation, the scripts were "crashing" at the point of trying to do these copies. A little analysis revealed that the real requirement was just to preserve the timestamps. So the `--preserve=timestamps` option was added and the `-p` option was removed. 

Mac OS X does not seem to provide support at all for long options like `--preserve=` to the `cp` command. So...`cp -p` will not work in the environment here at Washington University and `cp --preserve=timestamps` won't work under Mac OS X El Capitan.

Apologies for the frustration and head scratching this caused.
