### ISSUE TITLE
Pos=AP? or PA?

### ISSUE THREAD

**Issue by kfbs** [Washington-University/Pipelines#48]
In DiffusionPreprocessingBatch.7T.sh, 
		PosData="xxxx_AP.nii.gz"
		NegData="xxx_PA.nii.gz"
whereas in DiffPreprocPipeline_PreEddy.sh
		basePos="PA"
		baseNeg="AP"
I assume this does not make any difference for the result, but I want to make sure.
Also, the content of the files created in the Diffusion/rawdata directory does not match those in the unprocessed/Diffusion directory.

**Comment by glasserm** [comment]
Hi All,

There is a ticket below about the 7T diffusion script.  Is it possible that AP/PA mean something different at 3T and 7T because of the other settings sign being flipped?

Matt.

**Comment by glasserm** [comment]
Hi

I cannot remember which convention we used for Pos/Neg as AP/PA.

What is important however is to use as Pos the phase encoding direction that is acquired first in the scan. The final data are concatenated as Pos_Neg prior to eddy, so it makes more sense to use as first volume in this concatenated dataset (and therefore as reference space for distortion correction) the first b0 that is acquired during the scan.

Cheers
Stam


On 14 Aug 2017, at 18:49, Glasser, Matthew <glasserm@wustl.edu<mailto:glasserm@wustl.edu>> wrote:

Hi All,

There is a ticket below about the 7T diffusion script.  Is it possible that AP/PA mean something different at 3T and 7T because of the other settings sign being flipped?

Matt.

**Comment by glasserm** [comment]
We had tried to always make the field map have the correct polarity which does depend on the order of these things.

Matt.

From: Stamatios Sotiropoulos <stamatios.sotiropoulos@ndcn.ox.ac.uk<mailto:stamatios.sotiropoulos@ndcn.ox.ac.uk>>
Date: Monday, August 14, 2017 at 3:01 PM
To: Matt Glasser <glasserm@wustl.edu<mailto:glasserm@wustl.edu>>
Cc: Washington-University/Pipelines <reply@reply.github.com<mailto:reply@reply.github.com>>, Washington-University/Pipelines <Pipelines@noreply.github.com<mailto:Pipelines@noreply.github.com>>, Keith Jamison <kjamison@umn.edu<mailto:kjamison@umn.edu>>, "Harms, Michael" <mharms@wustl.edu<mailto:mharms@wustl.edu>>, "Brown, Tim" <tbbrown@wustl.edu<mailto:tbbrown@wustl.edu>>, Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Subject: Re: [Washington-University/Pipelines] Pos=AP? or PA? (#48)

Hi

I cannot remember which convention we used for Pos/Neg as AP/PA.

What is important however is to use as Pos the phase encoding direction that is acquired first in the scan. The final data are concatenated as Pos_Neg prior to eddy, so it makes more sense to use as first volume in this concatenated dataset (and therefore as reference space for distortion correction) the first b0 that is acquired during the scan.

Cheers
Stam


On 14 Aug 2017, at 18:49, Glasser, Matthew <glasserm@wustl.edu<mailto:glasserm@wustl.edu>> wrote:

Hi All,

There is a ticket below about the 7T diffusion script.  Is it possible that AP/PA mean something different at 3T and 7T because of the other settings sign being flipped?

Matt.

**Comment by glasserm** [comment]
FWIW while this may be an inconsistency in the current github, I don't
think this is what was actually run for our 7T diffusion data.

According the github, DiffPreprocPipeline_PreEddy.sh should be called with
--posData=*AP* --negData=*PA*, but the log file shows the opposite:

grep -n posData
/data/hcpdb/archive/HCP_1200/arc001/100610_7T/RESOURCES/Diffusion_preproc/100610.DiffusionPreprocessingHCP7T.HCP_Staging_7T.100610_7T_PreEddy.XNAT_PBS_job.sh.o1395281
:
391:DiffusionPreprocessingHCP7T_PreEddy.XNAT.sh: PreEddy_cmd: ... *--*
*posData*
=/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/
*100610_7T_DWI_dir71_PA*.nii.gz@
/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/
*100610_7T_DWI_dir72_PA*.nii.gz *--negData*
=/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/
*100610_7T_DWI_dir71_AP*.nii.gz@
/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/
*100610_7T_DWI_dir72_AP*.nii.gz ...

So then within PreEddy it performs:
imcp ...dir71_PA rawdata/PA_1
imcp ...dir72_PA rawdata/PA_2
imcp ...dir71_AP rawdata/AP_1
imcp ...dir72_AP rawdata/AP_2

and all is well.

I'm not sure where the discrepancy in the Batch.7T.sh arose, but *HCP data
should be fine.*

-Keith

**Comment by glasserm** [comment]
Hi,
I suspect that nothing changed in github, but rather that Tim Brown’s launching scripts for assigning arguments for DiffPreprocPipeline.sh are not entirely consistent with Examples/DiffusionPreprocessingBatch.7T.sh.  (In general, the various scripts in the Examples folder would benefit from some TLC).

i.e., Tim is assigning the “posData” input as the “PA” files
whereas in Examples/DiffusionPreprocessingBatch.7T.sh it suggests using the “AP” direction as the “PosData” files.

As the original query noted, embedded in DiffPreprocPipeline_PreEddy.sh is the following *hard coding* of “pos” and “neg”:

      if [ ${PEdir} -eq 1 ] ; then    # RL/LR phase encoding
            basePos="RL"
            baseNeg="LR"
      elif [ ${PEdir} -eq 2 ] ; then  # PA/AP phase encoding
            basePos="PA"
            baseNeg="AP"

Given the above, I actually see two issues here:
1) We should confirm that we’ve always launched DiffPreprocPipeline.sh using the “PA” files as the “posData” (both for HCP 7T, and Lifespan 1a/b pilots).  Then, we need to correct Examples/DiffusionPreprocessingBatch.7T.sh to reflect that.  (As a side benefit, that would bring the Diffusion and fMRIVolume Batch.7T.sh files into alignment with the “pos” direction being considered the “PA” direction for AP/PA phase encoding in both of them).

2) We should not hard code the Pos/Neg directions in DiffPreprocPipeline_PreEddy.sh using “RL/LR/AP/PA” strings as part of the file names.
As the code currently stands, if someone actually specified the “AP” scans as the “posData” input in DiffPreprocPipeline.sh, those input images would actually get copied info the rawdata directory as “PA_#.nii.gz”!  And while the correction would still work, this is clearly confusing.  In fact, I suspect this is what the user meant by
the name of the files created in the Diffusion/rawdata directory does not match those in the unprocessed/Diffusion directory.

i.e., I’m proposing that DiffPreprocPipeline_PreEddy.sh needs to respect what users have chosen to consider “pos” and “neg” in the earlier calling scripts.
[As we note with comments in the Examples/DiffusionPreprocessingBatch.sh (and 7T equivalent) file, the particular PE polarity assigned as “pos” or “neg” is not relevant, and the distortion and eddy current correction will be accurate either way].

My suggested solution to this latter issue is that we change that bit of code in DiffPreprocPipeline_PreEddy.sh to just the following:
basePos=”Pos”
baseNeg=”Neg”
so that the files in the rawdata dir are simply of the form {Pos,Neg}_?.{bval,bvec,nii.gz}

Other than needing to make a matching change to a similar hard-coded bit in basic_preproc.sh, I don’t think there are any downstream consequences to this change (based on a quick look).

Cheers,
-MH

--
Michael Harms, Ph.D.
-----------------------------------------------------------
Conte Center for the Neuroscience of Mental Disorders
Washington University School of Medicine
Department of Psychiatry, Box 8134
660 South Euclid Ave.                        Tel: 314-747-6173
St. Louis, MO  63110                                          Email: mharms@wustl.edu

From: Keith Jamison <kjamison@umn.edu>
Date: Tuesday, August 15, 2017 at 4:59 PM
To: "Glasser, Matthew" <glasserm@wustl.edu>
Cc: Stamatios Sotiropoulos <stamatios.sotiropoulos@ndcn.ox.ac.uk>, Washington-University/Pipelines <reply@reply.github.com>, Washington-University/Pipelines <Pipelines@noreply.github.com>, "Harms, Michael" <mharms@wustl.edu>, Timothy Brown <tbbrown@wustl.edu>, Subscribed <subscribed@noreply.github.com>
Subject: Re: [Washington-University/Pipelines] Pos=AP? or PA? (#48)

FWIW while this may be an inconsistency in the current github, I don't think this is what was actually run for our 7T diffusion data.
According the github, DiffPreprocPipeline_PreEddy.sh should be called with --posData=*AP* --negData=*PA*, but the log file shows the opposite:

grep -n posData /data/hcpdb/archive/HCP_1200/arc001/100610_7T/RESOURCES/Diffusion_preproc/100610.DiffusionPreprocessingHCP7T.HCP_Staging_7T.100610_7T_PreEddy.XNAT_PBS_job.sh.o1395281 :
391:DiffusionPreprocessingHCP7T_PreEddy.XNAT.sh<http://DiffusionPreprocessingHCP7T_PreEddy.XNAT.sh>: PreEddy_cmd: ... --posData=/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/100610_7T_DWI_dir71_PA.nii.gz@/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/100610_7T_DWI_dir72_PA.nii.gz --negData=/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/100610_7T_DWI_dir71_AP.nii.gz@/HCP/hcpdb/build_ssd/chpc/BUILD/HCP_Staging_7T/DiffusionPreprocessingHCP7T.100610.1477932396/100610/unprocessed/7T/Diffusion/100610_7T_DWI_dir72_AP.nii.gz ...

So then within PreEddy it performs:
imcp ...dir71_PA rawdata/PA_1
imcp ...dir72_PA rawdata/PA_2
imcp ...dir71_AP rawdata/AP_1
imcp ...dir72_AP rawdata/AP_2
and all is well.
I'm not sure where the discrepancy in the Batch.7T.sh<http://Batch.7T.sh> arose, but HCP data should be fine.
-Keith

On Mon, Aug 14, 2017 at 4:13 PM, Glasser, Matthew <glasserm@wustl.edu<mailto:glasserm@wustl.edu>> wrote:
We had tried to always make the field map have the correct polarity which does depend on the order of these things.

Matt.

From: Stamatios Sotiropoulos <stamatios.sotiropoulos@ndcn.ox.ac.uk<mailto:stamatios.sotiropoulos@ndcn.ox.ac.uk>>
Date: Monday, August 14, 2017 at 3:01 PM
To: Matt Glasser <glasserm@wustl.edu<mailto:glasserm@wustl.edu>>
Cc: Washington-University/Pipelines <reply@reply.github.com<mailto:reply@reply.github.com>>, Washington-University/Pipelines <Pipelines@noreply.github.com<mailto:Pipelines@noreply.github.com>>, Keith Jamison <kjamison@umn.edu<mailto:kjamison@umn.edu>>, "Harms, Michael" <mharms@wustl.edu<mailto:mharms@wustl.edu>>, "Brown, Tim" <tbbrown@wustl.edu<mailto:tbbrown@wustl.edu>>, Subscribed <subscribed@noreply.github.com<mailto:subscribed@noreply.github.com>>
Subject: Re: [Washington-University/Pipelines] Pos=AP? or PA? (#48)

Hi

I cannot remember which convention we used for Pos/Neg as AP/PA.

What is important however is to use as Pos the phase encoding direction that is acquired first in the scan. The final data are concatenated as Pos_Neg prior to eddy, so it makes more sense to use as first volume in this concatenated dataset (and therefore as reference space for distortion correction) the first b0 that is acquired during the scan.

Cheers
Stam


On 14 Aug 2017, at 18:49, Glasser, Matthew <glasserm@wustl.edu<mailto:glasserm@wustl.edu>> wrote:

Hi All,

There is a ticket below about the 7T diffusion script.  Is it possible that AP/PA mean something different at 3T and 7T because of the other settings sign being flipped?

Matt.
